# Generated by Django 5.1.7 on 2025-03-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0002_alter_choices_question_alter_questions_survey_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='question',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='survey',
        ),
        migrations.AddField(
            model_name='responses',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='responses',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
